name: BiznesRadar Multi Scraper

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 8 * * *"  # codziennie o 8:00 UTC

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        run: python scraper.py

      - name: Upload scraped data
        uses: actions/upload-artifact@v4
        with:
          name: profile_spolek
          path: profile_spolek.txt
